version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rockfall_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rockfall123
      MONGO_INITDB_DATABASE: rockfall_prediction
    volumes:
      - mongodb_data:/data/db
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - rockfall_network

  mongodb_express:
    image: mongo-express:1.0.0
    container_name: rockfall_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: rockfall123
      ME_CONFIG_MONGODB_URL: mongodb://admin:rockfall123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - rockfall_network

volumes:
  mongodb_data:

networks:
  rockfall_network:
    driver: bridge